### ISSUE TITLE
[Improvement] Default target name

### ISSUE THREAD

**Issue by rutrum** [Wafelack/rdfm#2]
By default it might be nice that the $dest of the add command is just the same directory relative to home.  That is, instead of specifying `rdfm add .vimrc .vimrc` it could by default infer the destination from `rdfm add .vimrc`.  Typically I'll want to use the destination file that reflects the structure in my home directory.

**Comment by Wafelack** [comment]
Hello,

You mean, when the command is issued with only one argument, replacing the tilde in the source path by the dotfiles path ?

Regards,
Wafelack.

**Comment by rutrum** [comment]
That is correct.  The home directory structure is typically how I've seen dotfiles organized, although the flexibility of changing locations is helpful (particularly for those files that pollute the home directory, like .vimrc .bashrc .bash_profiles etc)

**Comment by Wafelack** [comment]
Hello,

I added it, is it as you wanted ?

Regards,
Wafelack.
