### ISSUE TITLE
[Bug] Accidental remove of newlines when using remove command

### ISSUE THREAD

**Issue by rutrum** [Wafelack/rdfm#3]
This should reproduce my issue from a new install.
```
rdfm setup
rdfm add .vimrc .vimrc
rdfm add .vimrc vim/.vimrc
rdfm remove vim/.vimrc
```
That produces a rdfm file that appears invalid.
```
$ cat .dotfiles/dotfiles.rdfm
# This file is created by rdfm and is not intended for manual editing..vimrc->/home/rutrum/.dotfiles/.vimrc
```
That is, there are no newlines in the file anymore.

**Comment by Wafelack** [comment]
Hello,

Fixed in [0c7afd3](https://github.com/Wafelack/rdfm/commit/0c7afd3303753e4797f6343103f7216daaf09eae).

Regards,
Wafelack.
