### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by orhun** [Wafelack/rdfm#5]
Hey!
You need to commit `Cargo.lock` file because it's a binary project. See more info here: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
Also you can remove it from `.gitignore`: https://github.com/Wafelack/rdfm/blob/master/.gitignore#L2

**Comment by Wafelack** [comment]
Hello,
Ok, it is done.
